# Generated by Django 2.0.13 on 2019-10-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('rig_location', models.CharField(max_length=50)),
                ('well_bore_diameter', models.CharField(blank=True, default=None, max_length=50)),
                ('well_name', models.CharField(blank=True, default=None, max_length=50)),
                ('well_location', models.CharField(blank=True, default=None, max_length=50)),
                ('well_diameter', models.PositiveIntegerField(blank=True, default=None)),
                ('well_depth', models.PositiveIntegerField(blank=True, default=None)),
                ('raw_data_file', models.CharField(max_length=500)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
