# Generated by Django 2.0.13 on 2019-10-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RigApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rig',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='rig',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
