# Generated by Django 2.0.13 on 2019-10-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RigApp', '0002_auto_20191006_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rig',
            old_name='body',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='rig',
            old_name='author',
            new_name='raw_data_file',
        ),
        migrations.RenameField(
            model_name='rig',
            old_name='title',
            new_name='rig_location',
        ),
        migrations.RenameField(
            model_name='rig',
            old_name='location',
            new_name='well_bore_diameter',
        ),
        migrations.AddField(
            model_name='rig',
            name='well_depth',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='rig',
            name='well_diameter',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='rig',
            name='well_location',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='rig',
            name='well_name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='rig',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
