# Generated by Django 2.0.13 on 2019-10-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RigApp', '0003_auto_20191008_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='well_depth',
            field=models.PositiveIntegerField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='rig',
            name='well_diameter',
            field=models.PositiveIntegerField(blank=True, default=None, max_length=50),
        ),
    ]
