# Generated by Django 2.0.13 on 2019-10-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RigApp', '0005_auto_20191008_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rig',
            old_name='id',
            new_name='rig_number',
        ),
    ]
