# Generated by Django 2.0.13 on 2019-10-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RigApp', '0007_auto_20191008_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rig',
            name='well_depth',
        ),
        migrations.RemoveField(
            model_name='rig',
            name='well_diameter',
        ),
        migrations.RemoveField(
            model_name='rig',
            name='well_location',
        ),
        migrations.RemoveField(
            model_name='rig',
            name='well_name',
        ),
    ]
